### ISSUE TITLE
Api issues

### ISSUE THREAD

**Issue by LoryPelli** [styfle/packagephobia#1000]
Check api because there are some issues. One of them is that
https://packagephobia.com/v2/api.json?p=next doesn't work and the gateway times-out

**Comment by styfle** [comment]
Thanks, fixed

**Comment by LoryPelli** [comment]
> Thanks, fixed

I'm not sure if this was the only one, you should check api completely and also it seems to have slow response, are you able to check?

**Comment by LoryPelli** [comment]
I mean v2 endpoint
