### ISSUE TITLE
Package list

### ISSUE THREAD

**Issue by LoryPelli** [styfle/packagephobia#1001]
Add an endpoint with a list of supported packages

**Comment by styfle** [comment]
I don’t understand. Can you explain?

**Comment by LoryPelli** [comment]
> I don’t understand. Can you explain?

Endpoint where we can see all supported packages (there was one like this in the npm registry but it was removed)

**Comment by styfle** [comment]
I still don’t understand. 

Package Phobia is not a replacement for npm. It’s designed to show package size.
