### ISSUE TITLE
Add light mode/dark mode switcher

### ISSUE THREAD

**Issue by lorypelli** [styfle/packagephobia#1006]
I hate light mode

**Comment by styfle** [comment]
PR is welcome 👍

**Comment by ali963sy** [comment]
![Uploading Picsart_23-02-26_05-33-35-753.jpg…]()

**Comment by LoryPelli** [comment]
> ![Uploading Picsart_23-02-26_05-33-35-753.jpg…]()
> 

I can't see the image

**Comment by ali963sy** [comment]
~~4066f657d3da2bf61f3428581c444a4e59f0a205~~

**Comment by MathurAditya724** [comment]
Hey can I work on the PR, and also can I use `tailwindcss` for this?

**Comment by styfle** [comment]
You can work on it but not with tailwind.

In the future, we can choose to switch to tailwind but today it could be implemented with a separate stylesheet.

**Comment by MathurAditya724** [comment]
Okay sure
