### ISSUE TITLE
@ant-design/pro-editor timeout

### ISSUE THREAD

**Issue by arvinxx** [styfle/packagephobia#1008]
here are link: https://packagephobia.com/result?p=@ant-design/pro-editor

<img width="1058" alt="image" src="https://github.com/styfle/packagephobia/assets/28616219/e5da5771-f193-4b89-aafb-442ac998c8c9">

**Comment by styfle** [comment]
The timeout is set to 30 seconds so this package is likely very big and can't install in less than 30 seconds.

Running it locally, we can see that package has a massive amount of dependencies.

- Install Size: 173 MB
- Install Files: 53060

https://packagephobia.com/result?p=@ant-design/pro-editor@0.6.0
