### ISSUE TITLE
Add some spacing between sponsors

### ISSUE THREAD

**Issue by MathurAditya724** [styfle/packagephobia#1016]
- [ ] Add even spacing between them
<img width="177" alt="image" src="https://github.com/styfle/packagephobia/assets/57684218/aed66a79-bdb6-4a9f-a9aa-3dbd50bb1282">

**Comment by MathurAditya724** [comment]
I will create a PR, once #1015 is merged

**Comment by styfle** [comment]
Don't worry about this one. I am planning to drop Upstash now that Vercel has its own storage offering

https://vercel.com/blog/vercel-storage

**Comment by MathurAditya724** [comment]
That's great, but it really gives me an OCD attack when I come to your site 🙃. And I have already prepared the code, so can you please accept the PR, later? 🤞🏼

**Comment by MathurAditya724** [comment]
> Don't worry about this one. I am planning to drop Upstash now that Vercel has its own storage offering
> 
> https://vercel.com/blog/vercel-storage
> 
> In fact, I'll probably switch from Redis to Postgres which is better suited for these types of queries.

Btw have you started working on this? I would love to contribute to it

**Comment by styfle** [comment]
I haven’t started yet. I think the most challenging part will be creating a semver ORDER BY so that we don’t need to sort in JS and therefore minimize the result returned from the query. I haven’t researched if this is possible yet.
