### ISSUE TITLE
Error 504 GATEWAY_TIMEOUT for some packages

### ISSUE THREAD

**Issue by TheMikeyRoss** [styfle/packagephobia#1019]
Hi, 

I'm trying to install [Hawa UI kit](https://github.com/sikka-software/Hawa) in my project and I want to check the size but for some reason I keep getting serverless function timed out. I've tried it today and yesterday but to no avail

https://packagephobia.com/result?p=@sikka/hawa

**Comment by styfle** [comment]
Its taking longer than 30 seconds to install which means its likely very large.

See https://github.com/styfle/packagephobia/issues/1017#issuecomment-1789541267
