### ISSUE TITLE
Install size is of the new version package is huge despite on no-changes in the code

### ISSUE THREAD

**Issue by Yegorich555** [styfle/packagephobia#1025]
Go to https://packagephobia.com/result?p=webpack-mock-server
and you can notice that install size of last version is significant bigger then previous. But in last version changed only Readme.md file - added couple examples.
So `install size` looks wrong. Could you explain why?

<img width="800" alt="image" src="https://github.com/styfle/packagephobia/assets/229881/8a3671e6-a741-4d56-a170-5d5d6c9ac5e0">

**Comment by Yegorich555** [comment]
No package.json changes from previous release. I always use npm. Package itself 103kb. Previous releases shows about 4.3mb. And it fits more then 45.2Mb. How it can bigger in 10x times only after changing Readme.md and new publish I can't figure out. Moreover I've rechecked last release twice. Installed package looks good. Without extra files

**Comment by Yegorich555** [comment]
My npm version 9.8.1. Node 18.18.2.

**Comment by Pkmmte** [comment]
I second this. Our package size increased from 614kB to 15.3MB after a patch release with minimal changes: https://packagephobia.com/result?p=%40roboplay%2Frobo.js%40latest

After inspecting this with pkg-size.dev, I found that the reported 15.3MB somewhat matched only after including the required peer dependencies. In a way, I can see this as being a more accurate representation of its true size, but it also feels misleading as makes it look like this is its standalone size.

**Comment by styfle** [comment]
Yeah sounds like peerDependencies. 

This behavior was changed in npm CLI. From the docs:

> In npm versions 3 through 6, peerDependencies were not automatically installed, and would raise a warning if an invalid version of the peer dependency was found in the tree. As of npm v7, peerDependencies are installed by default.

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#peerdependencies

**Comment by Yegorich555** [comment]
I guess algorithm of calculating size should be updated and exclude installed peerDependencies from install-size report ?

**Comment by styfle** [comment]
I think package phobia should use the npm default because that is what the average user is going to use

**Comment by Pkmmte** [comment]
> I think package phobia should use the npm default because that is what the average user is going to use

I feel like including the additional peer dependency size gives a misleading impression to end users.

For example, one of our framework's selling points is its tiny 600 kB size. Including the library it is a framework of as a peer suddenly makes it feel like the framework itself is 15MB+, giving a false impression to end users we're trying to convert.

Just my opinion~

**Comment by Yegorich555** [comment]
@Pkmmte peerDependencies installed by the user in 99% separately. So it doesn't make sense to include ones in install size of specific package

**Comment by styfle** [comment]
I gave this some more thought and I agree that the behavior should match the old behavior since we have 5 years of data now.

I created PR #1028 and updated the latest [webpack-mock-server](https://packagephobia.com/result?p=webpack-mock-server) entry.
