### ISSUE TITLE
Anvaka visualisation for scoped packages

### ISSUE THREAD

**Issue by larsgw** [styfle/packagephobia#125]
The URL linking to the anvaka/npmgraph.an dependecy visualization is broken for scoped packages. This is because the forward slash should be escaped (well, at least that does work). Example ([Package Phobia page](https://packagephobia.now.sh/result?p=%40babel%2Fcore)):

    https://npm.anvaka.com/#/view/2d/@babel/core%3F

![npm anvaka com_ 1](https://user-images.githubusercontent.com/14018963/44879739-d7d0c000-acaa-11e8-9d76-ee4ad538025f.png)

**Comment by styfle** [comment]
Thanks for reporting this bug!
I will have a fix out shortly 😄
