### ISSUE TITLE
Allow for running locally against custom registries?

### ISSUE THREAD

**Issue by ansballard** [styfle/packagephobia#137]
So at work we use a private npm registry, and I wanted to see how simple it would be to spin up a local instance of this to check our private libraries. Turns out there's a single reference to https://registry.npmjs.com/${encodedPackage} in `src/util/npm-api.ts` (fetchManifest function) that handles all the registry calls, so making that configurable at build/run time means spinning up a local instance pointing to your custom registry with a single config and a local redis instance, which I think would be pretty cool.

Local docker redis for reference: `docker run --rm -it --name redis -p 14555:6379 redis`.

Thanks for the service, I love using this and bundlephobia!

**Comment by styfle** [comment]
Hi Aaron, I'm glad you like Package Phobia! 😄 

Are you suggesting using an env var for setting the private registry or making this a first-class feature of Package Phobia? I think I would prefer the first option.

**Comment by ansballard** [comment]
Definitely agree, I think a settable env var is plenty. I _guess_ being able to specify your registry on the fly would be cool, but I can't imagine that would be a heavily used feature, so probably not worth the dev time unless someone else wants it.
