### ISSUE TITLE
node package maintenance team request

### ISSUE THREAD

**Issue by ghinks** [styfle/packagephobia#308]
The node foundation is setting up a [package maintenance team](https://github.com/nodejs/package-maintenance) and we would like to have a point of contact with the package phobia team. 

The node package maintenance team has been tasked with writing the set of rules via which a verified team can step into and assist critical node packages if maintainers request help. 

We are thinking of incorporating the package phobia data into our procedures and would like a point of contact to talk further about it.

**Comment by styfle** [comment]
@ghinks Wonderful! I am the point of contact 😄

**Comment by ghinks** [comment]
Most excellent and thank you Steven. What the team would like to do is have a badge for packages that we support and are compliant with our package maintenance rules on the package phobia site.

The package maintenance team have built a [small tool](https://www.npmjs.com/package/package-compliant)

The idea is that,  we could add an icon in that site that link directly to us:

[Example](https://packagephobia.now.sh/result?p=package-compliant)
![image](https://user-images.githubusercontent.com/11404065/56832330-f43df000-686b-11e9-88e6-9c6851ae2f0e.png)

It is very early days for the package maintenance team, but as you can understand the first steps are writing up all the procedures for stepping in and assisting a package. We have identified first candidates. Package compliance is important, and the team really liked your tool.

So this is the start of a conversation about getting a badge for package compliance.

**Comment by styfle** [comment]
@ghinks Very cool!

All we need are these two things:

- svg for the icon
- url for the link

The svg goes in the [LinkedLogo](https://github.com/styfle/packagephobia/blob/3e8fbaf78215a7af5b3b7a893eb442dc2572dd50/src/components/LinkedLogo.tsx#L29) component and the link goes in the [LinkedLogos](https://github.com/styfle/packagephobia/blob/master/src/components/LinkedLogos.tsx#L14) component 👍

**Comment by Eomm** [comment]
Roger that, we will start soon working on this feature on our side and then integrate to it!

Thank you for the availability

**Comment by styfle** [comment]
@Eomm Is there anything you need from my side?

**Comment by Eomm** [comment]
Nope, we are still working on tooling and we just agree in a new JSON format to support.

Would you mind to leave this issue open until we will finish our modules?

**Comment by styfle** [comment]
@ghinks @Eomm I've attended many of the `@nodejs/package-maintenance` team meetings but haven't really heard of any talk of Package Phobia (although I admit I haven't attended in the last few months).

Is there anything else you need me to do? Can we close this issue?

**Comment by ghinks** [comment]
Pls close the issue, and thank you.
