### ISSUE TITLE
Add an API to get json data

### ISSUE THREAD

**Issue by styfle** [styfle/packagephobia#35]
Some tools may want to display this install size but need their own formatting such as

- https://github.com/netlify/staticgen/issues/359
- https://github.com/npm/www/issues/197
- https://github.com/npms-io/npms-www/issues/219

So it would be good to provide an API, maybe use `/api?p=packagename@version` which is similar to `/badge?p=packagename@version` but returns json instead of an image.

**Comment by styfle** [comment]
The API is available.

You can use the npm package name and version (cached result):

https://packagephobia.now.sh/api.json?p=next@5.1.0

Or simply the npm package name which will automatically use the latest version (never cached):

https://packagephobia.now.sh/api.json?p=next

**Comment by aleclarson** [comment]
Thank you for this! I'm going to fork https://github.com/wix/import-cost and use this instead. (That extension is known for gobbling CPU)

**Comment by styfle** [comment]
@aleclarson Thanks for letting me know!

I'll add it to the README when you finish it 😄
