### ISSUE TITLE
Update styles for mobile devices

### ISSUE THREAD

**Issue by JB1905** [styfle/packagephobia#379]
Hi!

I found some elements that could be improved on mobile devices (search button, text formatting etc.). I have already updated some of them in forked repository.
I also think it would be useful to update styles, e.g. use only CSS in JS or add Styled Components.

**Comment by styfle** [comment]
Would you like to create a PR so I can look at the changes?

**Comment by JB1905** [comment]
#380

**Comment by styfle** [comment]
Thanks! I merged #380 🎉
