### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by levy9527** [styfle/packagephobia#388]
- Input @toast-ui/vue-editor

![image](https://user-images.githubusercontent.com/9384365/65148065-0b1af400-da52-11e9-8b89-4ef8f314b3af.png)

- Click search

![image](https://user-images.githubusercontent.com/9384365/65148097-19691000-da52-11e9-8cab-2a7bfab2371a.png)

**Comment by styfle** [comment]
```
Error while executing:
undefined ls-remote -h -t ssh://git@github.com/seonim-ryu/Squire.git
```

`@toast-ui/vue-editor` depends on `tui-editor` which depends on `squire-rte` as a git url.

https://github.com/nhn/tui.editor/blob/d18cd6496e609fcf69515dad741dad6e11af990f/package.json#L98

Package Phobia doesn't work with git.

Perhaps you can convince `squire-rte` to publish to npm and update `tui-editor`.

**Comment by levy9527** [comment]
Ok, thanks for your help
