### ISSUE TITLE
A button to switch between the NPM and GitHub registry

### ISSUE THREAD

**Issue by szmarczak** [styfle/packagephobia#389]
https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

### Proposed look

![image](https://user-images.githubusercontent.com/36894700/65254352-6f928d80-dafc-11e9-9044-c3d835cb33b7.png)

### How to switch?

I suggest two new subdomains:

- npm.packagephobia.now.sh - for the NPM registry
- github.packagephobia.now.sh - for the GitHub registry

packagephobia.now.sh would work the same as npm.packagephobia.now.sh

#### Another solution:

`https://packagephobia.now.sh/result?p=got@9.6.0`
⬇️ 
`https://packagephobia.now.sh/result?package=got@9.6.0&registry=npm`

**Comment by styfle** [comment]
One thing to consider is that a package has dependencies that might live on npm and might live on github.

How do we reconcile the two? Or is the assumption that a package published to github only uses other github packages as dependencies?

https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry

https://github.com/search?package_type=npm&q=a&type=RegistryPackages

**Comment by szmarczak** [comment]
> One thing to consider is that a package has dependencies that might live on npm and might live on github.

https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#installing-a-package

> For packages from GitHub Package Registry, specify the full scoped package name, like @my-org/server. For packages from npmjs.com, specify the full name, like @babel/core or @lodash.

It handles that automatically.

Anyway, we still need `git` (#211) for the packages located in NPM:

https://docs.npmjs.com/files/package.json#dependencies
https://docs.npmjs.com/cli/install

While using NPM as the main registry, it will use `git` to fetch GitHub/GitLab/BitBucket/any git packages.

**Comment by styfle** [comment]
I'm going to close this as won't fix.

I don't have any plans to add `git` CLI at runtime and I don't see many public packages published to github registry.

You can fork Package Phobia and deploy with `process.env.NPM_REGISTRY_URL` set to the appropriate registry url.
