### ISSUE TITLE
Add `dns-prefetch` for badgen.net in results page

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#443]
Should improve slightly the results page load time

**Comment by styfle** [comment]
Sure!

Your suggesting adding `<link rel="dns-prefetch" href="https://badge.net">` to the `<head>`?

**Comment by XhmikosR** [comment]
Yup :)

I'm just not familiar with React to do this only for the results page (or in any pages there are links to badgen.net)

**Comment by styfle** [comment]
There's also preconnect

https://developers.google.com/web/fundamentals/performance/resource-prioritization#preconnect

**Comment by styfle** [comment]
I removed badgen.net in favor of the `badgen` dependency in PR #669.

You should notice faster loading times now 🙂

**Comment by XhmikosR** [comment]
Nice!
