### ISSUE TITLE
Error 500 with some packages

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#444]
We must hit a timeout or something, but whenever I try https://packagephobia.now.sh/result?p=critical@1.3.2 I git Error 500

Not sure how to solve this. I mean, you could increase the process timeout, but then it might affect the whole site performance.

**Comment by XhmikosR** [comment]
Actually it seems to only happen with v1.3.2, so it's not a matter of the package size which is good.

Not sure what the exact error is since as a user I just see an Error 500. Maybe this could be improved?

**Comment by styfle** [comment]
The error is out of disk space. I can't increase disk space but I can increase memory.

**Comment by XhmikosR** [comment]
Perfect, thanks!

**Comment by XhmikosR** [comment]
Actually it happens with https://packagephobia.now.sh/result?p=critical@1.1.1 and https://packagephobia.now.sh/result?p=critical@1.0.0 and older version too.

**Comment by styfle** [comment]
Maybe the timeout needs to increase. These are really big packages. Try #448
