### ISSUE TITLE
Tighten HTTP headers

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#446]
* https://observatory.mozilla.org/analyze/packagephobia.now.sh
* https://securityheaders.com/?q=https%3A%2F%2Fpackagephobia.now.sh%2F&hide=on&followRedirects=on

Personally on Express I use [helmet](https://github.com/helmetjs/helmet), for example:

https://github.com/MaxCDN/bootstrapcdn/blob/develop/app.js#L125-L147

which results in these:

* https://securityheaders.com/?q=https%3A%2F%2Fwww.bootstrapcdn.com%2F&hide=on&followRedirects=on
* https://observatory.mozilla.org/analyze/www.bootstrapcdn.com

CSP should be left last, but the other headers should be easy to add :)

**Comment by styfle** [comment]
There are no logins, no cookies, and no javascript on this page (besides GA) 😄 

For the sake of the letter grade, I suppose its easy enough to add those headers.
