### ISSUE TITLE
Problem with label for longer package versions

### ISSUE THREAD

**Issue by JB1905** [styfle/packagephobia#451]
<img width="813" alt="Zrzut ekranu 2019-11-13 o 21 13 01" src="https://user-images.githubusercontent.com/28870390/68800864-27ef3480-065b-11ea-81ff-d32e96eb857e.png">

Labels could appear cropped (e.g. with `text-overflow: ellipsis`) and the full name would appear when you hover over the chart

**Comment by styfle** [comment]
Thanks for reporting! Would you like to submit a PR?

**Comment by JB1905** [comment]
Yes, I will check this and submit PR
