### ISSUE TITLE
Incorrect links sizing when details tag is open on smaller screens

### ISSUE THREAD

**Issue by JB1905** [styfle/packagephobia#452]
<img width="335" alt="Zrzut ekranu 2019-11-13 o 21 12 27" src="https://user-images.githubusercontent.com/28870390/68801120-b4015c00-065b-11ea-9684-ea6da527d41b.png">

Details tag could be replaced by component with `position: absolute` and show/hide toggle button

**Comment by kanhaiyaagrawal01** [comment]
Hey @styfle I would like to take this up

**Comment by styfle** [comment]
@kanhaiyaagrawal01 That would be great, thanks!

**Comment by styfle** [comment]
Is this still an issue?

I tried with an iPhone 5 (320px width) and it looks fine to me.

Here's a screenshot:

<img src="https://user-images.githubusercontent.com/229881/103464948-cb8b2080-4d05-11eb-9e23-ea4cf9f95b5a.png" width=320 />

**Comment by JB1905** [comment]
<img src="https://user-images.githubusercontent.com/28870390/103467675-b89e3d80-4d51-11eb-8460-8292461fad55.PNG" width="300"/>

**Comment by styfle** [comment]
I see now 🙂 

PR #674 will fix it
