### ISSUE TITLE
Bug: hard links are counted twice when calculating size

### ISSUE THREAD

**Issue by styfle** [styfle/packagephobia#47]
There is a bug when calculating the size of `full-icu` package where a hard link is counted twice.

(shout out to @srl295 for reporting this bug 👍)

Example: [full-icu@1.0.3](https://packagephobia.now.sh/result?p=full-icu@1.0.3) reports 2x the size of v1.0.2 because of a [hardlink](https://github.com/unicode-org/full-icu-npm/commit/a32c2bec2d98fd0ba98fa2c1ac27d85082e82711) to the data file. 

I believe the solution is to keep a `Set()` of the seen [inode](https://nodejs.org/api/fs.html#fs_stats_ino) numbers so that we don't count the same `inode` twice. More info in this [so question](https://stackoverflow.com/a/31825298/266535).

**Comment by srl295** [comment]
One of the versions showed 3x the size

OK, obligatory: It might increase your package size :) looks like there's https://www.npmjs.com/package/diskusage-ng which just calls `df`, in any event it might be better to put this logic in a separate module (maybe a PR into  https://www.npmjs.com/package/get-folder-size   which is basically like your function)

**Comment by srl295** [comment]
yes and https://packagephobia.now.sh/result?p=full-icu@1.1.2 shows 76 MB

**Comment by srl295** [comment]
anyway full-icu is a very strange package. It postinstalls a different package depending on your node version, or perhaps nothing at all.

**Comment by srl295** [comment]
related https://github.com/unicode-org/full-icu-npm/issues/5

**Comment by styfle** [comment]
I added a fix for hardlinks.
It looks like git doesn't even preserve hardlinks so I couldn't easily add a test case for travis-ci to run.

This fixed the full-icu reported size but there is one version, full-icu@1.1.2, that still looks larger, however this is reproducible by running the following:


```sh
mkdir example
cd example
npm init -y
npm install --save full-icu@1.1.2
du -sh . # 51M
```

I'm closing this issue as fixed.
