### ISSUE TITLE
'View <project> at graph' link broken

### ISSUE THREAD

**Issue by ArnaudBuchholz** [styfle/packagephobia#501]
The current link shows
[`https://npm.anvaka.com/#!/view/2d/reserve`](https://npm.anvaka.com/#!/view/2d/reserve)
But it should be
[`https://npm.anvaka.com/#/view/2d/reserve`](https://npm.anvaka.com/#/view/2d/reserve)

The extra ! should be removed

**Comment by styfle** [comment]
Thanks! Looks like they changed the URL pattern a bit but this is an easy fix. #502
