### ISSUE TITLE
compare page: link to the packages

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#565]
For example: <https://packagephobia.now.sh/result?p=axios%2Cgaxios>

Also maybe it would be possible to show the version of the packages we are comparing, if no version is passed? Right now the comparison is for the latest versions of the packages but this isn't reflected :)

Thanks!

**Comment by styfle** [comment]
Sounds good! Do you want to submit a PR?

**Comment by XhmikosR** [comment]
I'm familiar with the codebase and also time™ 🙂

I mostly opened this so that there's an issue open to track the request, no pressure.

**Comment by styfle** [comment]
Ah yes, "time™" 🙂 

I found some and fix this, thanks!

**Comment by XhmikosR** [comment]
Perfect, thank you!
