### ISSUE TITLE
Uptime?

### ISSUE THREAD

**Issue by AbhigyanKumar** [styfle/packagephobia#596]
# No uptime stats
I don't see any website uptime statistics. I saw that there is an uptime tag which has a "Resource fetching" issue.

**Comment by styfle** [comment]
Ironically, it looks like uptimerobot.com is down.

![uptimerobot](https://user-images.githubusercontent.com/229881/86883063-4d83ef00-c0bf-11ea-94e9-642b7e0854c8.png)

**Comment by AbhigyanKumar** [comment]
I think it would be better to fix it soon.

**Comment by styfle** [comment]
![image](https://user-images.githubusercontent.com/229881/87170754-bfb32a00-c29f-11ea-8352-9f4b025114c1.png)
