### ISSUE TITLE
Tags are resolved in input

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#684]
Hey, @styfle!

So, I was playing today with packagephobia trying to compare 4 packages with their tags. Example: <https://packagephobia.com/result?p=npm%406.14.11%2Cnpm%40next-7%2Cyarn%401.22.10%2Cyarn%40berry>

Now, this works fine, and the tags are properly resolved in the results. But it seems the input changes to the resolved version, while the URL is the original one.

Wouldn't it make more sense if the input was kept the same too like what was originally used?

<img src="https://user-images.githubusercontent.com/349621/105708326-f7707f00-5f1c-11eb-8fd0-4bedaa181ad8.png" alt="image" width="400">

**Comment by styfle** [comment]
> the input changes to the resolved version, while the URL is the original one.

I see what you mean. This is probably because the same object is shared everywhere the code.

We would need to save the user's input on the object as well.

Feel free to submit a PR if you can fix it 🙂

**Comment by styfle** [comment]
This will be fixed in PR #699 👍

**Comment by XhmikosR** [comment]
@styfle it seems https://packagephobia.com/result?p=npm%40latest-6%2Cnpm%40latest broke somewhere in the way?

**Comment by styfle** [comment]
Hmm, it seems like it was fixed for the original URL at the top when npm packages are mixed but the same package with multiple versions is not working as expected. https://packagephobia.com/result?p=npm%40latest-6%2Cnpm%407.8.0

**Comment by styfle** [comment]
Ok should be fixed now 👍

**Comment by XhmikosR** [comment]
Perfect, thank you!
