### ISSUE TITLE
500 internal server error with Windows only packages

### ISSUE THREAD

**Issue by eight04** [styfle/packagephobia#70]
I get 500 error while searching [`@eight04/start-browser`](https://www.npmjs.com/package/@eight04/start-browser):
https://packagephobia.now.sh/result?p=%40eight04%2Fstart-browser
![image](https://user-images.githubusercontent.com/1324510/40218044-17475448-5aa2-11e8-8e83-07bfaec2b1e6.png)

It works fine with [`@angular/cli`](https://www.npmjs.com/package/@angular/cli):
https://packagephobia.now.sh/result?p=%40angular%2Fcli
![image](https://user-images.githubusercontent.com/1324510/40218078-41f6eb4a-5aa2-11e8-9e38-3d95eba55b90.png)

**Comment by styfle** [comment]
Thanks for the bug report! 

I’m looking into this error.

**Comment by styfle** [comment]
It looks like this package depends on **regedit** which is Windows only. 

Package Phobia is running on a Linux server so it can’t install the package and calculate the size. 

```
npm ERR! code EBADPLATFORM
(3m)
npm ERR! notsup Unsupported platform for regedit@3.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
(3m)
npm ERR! notsup Valid OS:    win32
(3m)
npm ERR! notsup Valid Arch:  any
(3m)
npm ERR! notsup Actual OS:   linux
(3m)
npm ERR! notsup Actual Arch: x64
(3m)
(3m)
npm ERR! A complete log of this run can be found in:
(3m)
npm ERR!     /home/nowuser/.npm/_logs/2018-05-18T21_32_59_153Z-debug.log
(3m)
(3m)
Calculated size of @angular/cli@6.0.0 in 20.79s
```

**Comment by eight04** [comment]
:+1: Maybe it can tell the user why the installation failed (e.g. print the error log) instead of just showing 500 error page.

**Comment by styfle** [comment]
Thanks for the suggestion 👍 

I'll look into a better way to display error logs.
In the meantime, the logs are available if you visit `https://packagephobia.now.sh/_logs`

If Package Phobia keeps gaining popularity and I can somehow get free hosting, I could host 3 versions: one for Linux, Windows, and Mac OS. This would solve the Arch specific packages such as `regedit`, or packages that install different things depending on Arch such as `puppeteer`.

I just need to think through the GUI 🤔 

Related: https://github.com/GoogleChrome/puppeteer/pull/2552
