### ISSUE TITLE
https://packagephobia.com/result?p=ui5-test-runner

### ISSUE THREAD

**Issue by ArnaudBuchholz** [styfle/packagephobia#744]
This always lead to a 500 internal server error. It seems to be related to puppetter dependency :
https://packagephobia.com/result?p=puppetter

**Comment by styfle** [comment]
Yeah it’s too big now, here’s the error message

> running npm install in /tmp...
> puppeteer@9.1.1 install /tmp/tmp-package0.3844964230577421/node_modules/puppeteer
> node install.js
> ERROR: Failed to set up Chromium r869685! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
> [Error: ENOSPC: no space left on device, write]

**Comment by styfle** [comment]
Here’s the last versions we could measure: https://packagephobia.com/result?p=puppeteer@5.3.1

**Comment by ArnaudBuchholz** [comment]
What about setting PUPPETEER_SKIP_DOWNLOAD ?

**Comment by styfle** [comment]
That would defeat the purpose of Package Phobia because you wouldn’t be measuring the install size anymore

**Comment by ArnaudBuchholz** [comment]
Indeed... quick question : do you cache the results or do you evaluate the size on each request ? If cached, could there be a way to workaround the issue by injecting a value in the cache ?

**Comment by styfle** [comment]
Its cached in redis

Thats why you're able to see the previous values here https://packagephobia.com/result?p=puppeteer@5.3.1
