### ISSUE TITLE
upload lock file

### ISSUE THREAD

**Issue by jimmywarting** [styfle/packagephobia#775]
I work at a company that like to keep it's package private, I was wondering if it would be possible to just upload a package-lock.json or yarn.lock that both includes all packages that are being installed even those at `@my_private_org/test_runner`

it would probably be faster to scan it then traversing a single package.json

**Comment by styfle** [comment]
If you need access to a private registry, you would need to fork Package Phobia and deploy with the `NPM_REGISTRY_URL ` environment variable set to your private registry url.

https://github.com/styfle/packagephobia/blob/62becabd2d7b38264874cb438a8c83900da18136/src/util/npm-api.ts#L4
