### ISSUE TITLE
Add search results page on PackagePhobia

### ISSUE THREAD

**Issue by trivikr** [styfle/packagephobia#832]
### Is your feature request related to a problem? Please describe.
If package name does not exist, PackagePhobia website does not respond.
* Visit https://packagephobia.com/
* Search for non-existent package, like `@aws-sdk/`
* The website will not respond.

### Describe the solution you'd like
If the package for the searched query does not exist, show search results with links to packages.

For example, imagine the query is `@aws-sdk/` for package which doesn't exist.
The website can route to `/search?q=%40aws-sdk%2F` just like [npmjs](https://www.npmjs.com/search?q=%40aws-sdk%2F).

The search results page can reference to individual packages which share the search query. For example, the page for `@aws-sdk/client-s3` is `/result?p=@aws-sdk/client-s3`

### Describe alternatives you've considered
Hosting a different search engine for packagephobia.

### Additional context
This is in reference to blog post on reduction of publish size of modular AWS SDK for JavaScript (v3) announced in [tweet](https://twitter.com/trivikram/status/1446596564969930753).
I wanted to provide link to list page with search query `@aws-sdk/` from the blog post. But such feature doesn't exist.

**Comment by styfle** [comment]
You can use commas to show multiple packages like this:

https://packagephobia.com/result?p=%40aws-sdk%2Fmd5-js%2C%40aws-sdk%2Ftypes%2C%40aws-sdk%2Fcredential-provider-node

**Comment by styfle** [comment]
Your use case doesn't seem so much like search though.

It sounds more like you want to list all packages in a specific [scope](https://docs.npmjs.com/cli/v7/using-npm/scope), in this case `@aws-sdk`.

Or are there other use cases for search?

**Comment by styfle** [comment]
Sounds like an interesting feature!

I'm not planning to implement search now since Package Phobia isn't designed for discovery like npmjs.com or https://npms.io

But I'll leave this open so others can upvote and we can see if others are interested in this feature 👍

**Comment by styfle** [comment]
Closing since there have been no upvotes
