### ISSUE TITLE
Update to the latest npm

### ISSUE THREAD

**Issue by XhmikosR** [styfle/packagephobia#891]
Just opening the issue to track this. npm 8.x should be a lot faster but I know they've changed the API, so I'm not sure how easy this will be.

**Comment by styfle** [comment]
Since npm 8 [dropped support](https://github.com/npm/cli/releases/tag/v8.0.0) for `require('npm')` programatic access, we might need to switch to a different package manager. Looks like [pnpm](
https://github.com/pnpm/pnpm/issues/3482#issuecomment-966914916) might work.

**Comment by styfle** [comment]
I switched to yarn 2 in #959 since npm 6 was having problems with node 16
