### ISSUE TITLE
PackagePhobia is returning 504 Gateway Timeout for new versions

### ISSUE THREAD

**Issue by trivikr** [styfle/packagephobia#892]
Example: https://packagephobia.com/result?p=@aws-sdk/client-sts@3.47.0

<details>
<summary>Screenshot</summary>

<img width="774" alt="Screen Shot 2022-01-14 at 8 57 07 PM" src="https://user-images.githubusercontent.com/16024985/149609578-cb9c4f02-45d8-4a3e-9af3-4ba741904bcb.png">

</details>

<details>
<summary>Message shown</summary>

---

This Serverless Function has timed out.

Your connection is working correctly.

Vercel is working correctly.

504: GATEWAY_TIMEOUT
Code: FUNCTION_INVOCATION_TIMEOUT
ID: pdx1::wph4r-1642222657862-2edc4722679d

If you are a visitor, contact the website owner or try again later.
If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT) and [check the logs](https://packagephobia.com/_logs).

---

</details>

For older version it's working fine https://packagephobia.com/result?p=@aws-sdk/client-sts@3.36.1

**Comment by styfle** [comment]
Looks like its [working now](https://user-images.githubusercontent.com/229881/149638510-a4729962-f5bd-47c4-86d2-68ccf3bb2aa5.png). Are you still seeing issues?
