### ISSUE TITLE
Error: This Serverless Function has crashed

### ISSUE THREAD

**Issue by doinkythederp** [styfle/packagephobia#927]
The server is *sometimes* responding with an error when I view the website. I don't have as much debug info as I'd like, but here's what I know:

- The URL: https://packagephobia.com/result?p=nw
- The browser: Safari on iOS 15.3.1
- The message:
  500: INTERNAL_SERVER_ERROR
  Code: FUNCTION_INVOCATION_FAILED

**Comment by styfle** [comment]
I'm guessing it ran out of disk space.

Looks like its working now.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/229881/162331102-a8b85742-ce44-47a1-abd4-88bdb089d056.png">

**Comment by doinkythederp** [comment]
Seems to be working for me too.
