### ISSUE TITLE
Investigating `esno` returns 500 internal server error

### ISSUE THREAD

**Issue by yudai-nkt** [styfle/packagephobia#958]
I wanted to compare the size of `tsm` and `esno`, but the latter package result in a 500 error. Visiting https://packagephobia.com/result?p=esno shows the following message.

> This Serverless Function has crashed.
> 
> Your connection is working correctly.
> 
> Vercel is working correctly.
> 
> 500: INTERNAL_SERVER_ERROR
> Code: FUNCTION_INVOCATION_FAILED
> ID: hnd1::fcgjg-1653998369391-e837880bb187
> 
> If you are a visitor, contact the website owner or try again later.
> If you are the owner, [learn how to fix the error](https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED) and > [check the logs](https://packagephobia.com/_logs).

<details>
<summary>Result of <code>curl --insecure  --verbose "https://packagephobia.com/v2/api.json?p=esno":</code></summary>

```console
*   Trying 76.76.21.98...
* TCP_NODELAY set
* Connected to packagephobia.com (76.76.21.98) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=packagephobia.com
*  start date: May 22 21:32:23 2022 GMT
*  expire date: Aug 20 21:32:22 2022 GMT
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe6fe806400)
> GET /v2/api.json?p=esno HTTP/2
> Host: packagephobia.com
> User-Agent: curl/7.54.0
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 500
< date: Tue, 31 May 2022 11:55:18 GMT
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< x-frame-options: DENY
< x-vercel-error: FUNCTION_INVOCATION_FAILED
< content-length: 56
< server: Vercel
< x-vercel-id: hnd1::b6ztt-1653998118881-cc2ef595aa82
< strict-transport-security: max-age=63072000
< cache-control: public, max-age=0, must-revalidate
< x-vercel-cache: MISS
<
A server error has occurred

FUNCTION_INVOCATION_FAILED
* Connection #0 to host packagephobia.com left intact
```

</details>

Some old issues say these 500 errors come from the node-gyp and packagephobia does not have a plan to support it. Neither `tsm` nor `esno` are pure-JavaScript packages, but they both depend on ESbuild. So I don't really see any big differences between them.

**Comment by styfle** [comment]
Upgraded but its still timing out. This package is just too big. You can confirm with this:

```
mkdir example
cd example
npm init -y
npm install esno
du -sh node_modules
```

**Comment by styfle** [comment]
This will be fixed in https://github.com/styfle/packagephobia/pull/976

**Comment by yudai-nkt** [comment]
Yup, both https://packagephobia-git-try-yarn3-packagephobia.vercel.app/result?p=esno and https://packagephobia-git-try-yarn3-packagephobia.vercel.app/result?p=tsx work well. Thanks :heart:
