### ISSUE TITLE
tsx returns 500 Internal Server Error

### ISSUE THREAD

**Issue by privatenumber** [styfle/packagephobia#964]
I get a 500 Internal Server Error when looking up `tsx`:
https://packagephobia.com/result?p=tsx

When testing size locally, its only `9.8 M`:
```
$ cat package.json
{
  "devDependencies": {
    "tsx": "^3.4.2"
  }
}
$ du -sh node_modules
9.8M	node_modules
```

Since there are packages that are [way larger](https://packagephobia.com/result?p=next), I don't think size is the issue.

**Comment by styfle** [comment]
This will be fixed in https://github.com/styfle/packagephobia/pull/976
