### ISSUE TITLE
Size seems off sometimes

### ISSUE THREAD

**Issue by janniks** [styfle/packagephobia#978]
On some packages e.g. @stacks/common it seems the size is very off.

https://packagephobia.com/result?p=%40stacks%2Fcommon → to compare https://bundlephobia.com/package/@stacks/common@4.3.0

Can you help me understand where this comes from? Would love to contribute and maybe help add some of the features still missing, e.g.: detect tree-shakeability, composition of deps, side-effect-freeness, number of deps

♥️ love packagephobia as bundlephobia is pretty much broken and down all the time 🙃

**Comment by styfle** [comment]
Hi @janniks 

Checkout the readme for an [explanation](https://github.com/styfle/packagephobia/blob/main/README.md#what-is-the-purpose) and [comparison](https://github.com/styfle/packagephobia/blob/main/README.md#how-is-this-different)

**Comment by janniks** [comment]
Oh, got it — sorry about that! 🙏
