### ISSUE TITLE
Internal Server Error when package doesn't exit/found

### ISSUE THREAD

**Issue by aziyatali** [styfle/packagephobia#989]
We should handle the case when package doesn't exit or match with any existing. 
Currently it shows Internal Server Error (500).

**Comment by styfle** [comment]
Sounds good. Want to submit a PR?

**Comment by aziyatali** [comment]
@styfle  Sure, sure. I will submit a PR and let you know!

**Comment by aziyatali** [comment]
@styfle  Currently, I am unable to run packagephobia locally for the reason it requires to login Vercel first(It is asking for SMS verification and my sim-card is not working). I will be back asap I handle this issue.

**Comment by styfle** [comment]
@aziyatali Usually SMS verification is only needed if your linked github account is new. Did you use the "Continue with GitHub" button to sign up for Vercel?

**Comment by aziyatali** [comment]
@styfle Yes, and it is linking me to the verification page unfortunately. I did a PR request but it was uncomplete. As soona as verify it then I will be back

**Comment by styfle** [comment]
@aziyatali Please try logging in again, should work this time 👍
