### ISSUE TITLE
Displayed sizes are super wrong

### ISSUE THREAD

**Issue by probablyup** [styfle/packagephobia#995]
For example: https://packagephobia.com/result?p=styled-components

styled-components is like 15kB gzipped. It seems like you’re summing the whole dist directory (including source maps) or something which is very wrong.

**Comment by styfle** [comment]
The size is correct, you are misunderstanding what Package Phobia is measuring.

See the readme https://github.com/styfle/packagephobia/blob/main/README.md#how-is-this-different

Also see the footer of https://packagephobia.com
